/*
 * This source file was generated by the Gradle 'init' task
 */
package com.willcounter.api

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    // Application entry point
}
